//! Tauri-facing wire types for the agent runtime IPC surface.
//!
//! Phase 2.3 extends the Phase 2.2 [`AgentChatRequest`] with the full
//! per-turn payload the frontend now sends:
//!
//! - [`crate::api::ProviderConfigSnapshot`] — opaque provider config
//!   passed straight through to the API factory.
//! - Pre-rendered system prompt (the frontend's
//!   `composeAgentSystemPrompt(...)` already does this composition; the
//!   runtime never composes prompts itself).
//! - Optional IDE context block — wrapped in `<ide_context>...
//!   </ide_context>` and prepended to the user message at API-call time
//!   while the persisted JSONL bubble keeps the clean `user_message`.
//! - Tool catalogue (each entry's JSON-Schema parameters) — every name
//!   in this list resolves to a [`crate::agent_runtime::bridge::FrontendBridgeExecutor`]
//!   in the per-turn registry.
//! - Sampling temperature, max output tokens, thinking flag — per-turn
//!   overrides over the defaults baked into [`crate::agent_runtime::conversation::RuntimeConfig`].
//!
//! Wire format: `#[serde(rename_all = "camelCase")]`. The frontend
//! sends `{ "turnId": "...", "providerConfig": {...},
//! "systemPrompt": "...", "ideContext": "...", "tools": [...],
//! "temperature": 0.7, "maxOutputTokens": 4096,
//! "thinkingEnabled": true }`. This is a deliberate change from the
//! Phase 2.2 snake_case shape — `agent_chat_v2` is brand-new IPC and
//! nothing in the live frontend depends on the old shape.
//!
//! [`AgentEventEnvelope`] keeps the Phase 2.2 snake_case shape because
//! the streaming envelope already shipped with that format and the
//! frontend's Phase 2.2 listener stayed compatible with that side of
//! the contract.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

use super::events::AssistantEvent;

/// Frontend → backend request to start one agent turn.
///
/// `turn_id` is a ULID generated by the frontend so it can correlate
/// the streamed [`AgentEventEnvelope`]s with the originating call
/// without an extra round trip. The frontend treats the envelope
/// stream as the authoritative ordering — `turn_id` is the join key.
///
/// Wire format: `rename_all = "camelCase"`. See module docs for the
/// JSON shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentChatRequest {
    // ── Phase 2.2 fields ───────────────────────────────────────────
    /// ULID generated client-side. Used as the event-channel
    /// correlation id and the bridge oneshot key.
    pub turn_id: String,
    /// Identifier of the chat thread this turn belongs to. Maps to the
    /// JSONL log under `<agent_root>/agent_v2/{thread_id}.jsonl`.
    pub thread_id: String,
    /// Raw user input. The runtime persists this verbatim into the
    /// session JSONL; for the API request it is wrapped with
    /// `ide_context` (see below) on the first iteration only.
    pub user_message: String,
    /// LLM provider identifier. Used by the
    /// [`crate::commands::agent_v2::AgentRegistry`] for telemetry; the
    /// real provider routing is done by the [`provider_config`] field
    /// below (which carries its own `provider_id`).
    pub provider_id: String,
    /// Model name to send to the provider (e.g.
    /// `"claude-3-7-sonnet-20250219"`). Echoed by the runtime into the
    /// session log on the first turn for telemetry.
    pub model: String,
    /// Optional workspace root. Tools that touch the filesystem
    /// resolve paths against this root.
    pub workspace_path: Option<String>,

    // ── Phase 2.3 NEW fields ───────────────────────────────────────
    /// Full provider configuration snapshot (api_key, base_url,
    /// custom_headers, custom_params, …). Sent verbatim from the
    /// frontend's `useSettingsStore.getLLMConfig()`. The runtime
    /// passes it unchanged to [`crate::api::build_api_client`]; the
    /// adapters are the only code that interprets the inner fields.
    pub provider_config: crate::api::ProviderConfigSnapshot,

    /// Pre-rendered system prompt. Built by the frontend's existing
    /// `composeAgentSystemPrompt(...)` machinery — the runtime never
    /// composes system prompts itself.
    #[serde(default)]
    pub system_prompt: Option<String>,

    /// IDE context block (from `getIDEContext` / `buildQueryContext`).
    /// The runtime concatenates `<ide_context>...</ide_context>` ahead
    /// of the user's clean text when assembling the API request, but
    /// persists `user_message` verbatim so the JSONL bubble stays
    /// clean. Match the existing TS behaviour in `agent-service.ts`.
    #[serde(default)]
    pub ide_context: Option<String>,

    /// Tool catalogue advertised to the model. Each entry's
    /// `parameters` is a JSON-Schema object describing the tool's
    /// input. Phase 2.3 forwards every tool name through the
    /// `FrontendBridgeExecutor` (see `crate::agent_runtime::bridge`)
    /// — the Rust tool registry stays empty until Phase 3 ports the
    /// native executors.
    #[serde(default)]
    pub tools: Vec<AllowedTool>,

    /// Sampling temperature. `None` defers to the provider preset
    /// default (some, like DeepSeek's reasoner, ignore it entirely).
    #[serde(default)]
    pub temperature: Option<f32>,

    /// Hard cap per API call. `None` defers to
    /// [`crate::agent_runtime::conversation::RuntimeConfig::default_max_output_tokens`].
    #[serde(default)]
    pub max_output_tokens: Option<u32>,

    /// Whether to enable extended thinking. Honoured only when the
    /// provider preset advertises thinking support; the impl silently
    /// drops it otherwise. `None` means "use the default" (`false`).
    #[serde(default)]
    pub thinking_enabled: Option<bool>,

    /// Provider's advertised total context window (input + output) for
    /// the chosen model, in tokens. When set, the runtime applies a
    /// budget-aware trim before each API call: older turns get dropped
    /// (from oldest first, always preserving the last two user-anchored
    /// turns) once the persisted session would exceed ~75% of
    /// `(context_window - max_output_tokens * 1.1)`. The persisted JSONL
    /// is untouched — only the API view is trimmed.
    ///
    /// `None` disables trimming entirely. Callers that don't pass a
    /// window get the legacy behaviour (whole session sent every turn).
    #[serde(default)]
    pub context_window: Option<u32>,
}

/// One tool entry in [`AgentChatRequest::tools`].
///
/// Maps onto Aurora's TypeScript `ToolDefinition` shape: `name`,
/// `description`, and a JSON-Schema `parameters` object the runtime
/// hands to the model verbatim. The bridge dispatches calls of this
/// name back to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllowedTool {
    pub name: String,
    pub description: String,
    /// JSON Schema object describing the tool's input.
    pub parameters: serde_json::Value,
}

/// Backend → frontend event envelope.
///
/// `seq` is monotonic per `turn_id`, starting at 0 with the first
/// event of a turn. The frontend uses it to detect dropped or out-of-
/// order events; in correct operation it always increments by 1.
///
/// `Serialize`-only because envelopes flow strictly Rust → frontend.
/// Wire format keeps the Phase 2.2 snake_case shape.
#[derive(Debug, Clone, Serialize)]
pub struct AgentEventEnvelope {
    pub turn_id: String,
    pub seq: u64,
    pub event: AssistantEvent,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent_runtime::types::TokenUsage;
    use crate::api::ProviderConfigSnapshot;

    fn minimal_provider_config() -> ProviderConfigSnapshot {
        ProviderConfigSnapshot {
            provider_id: "anthropic".into(),
            base_url: "https://api.anthropic.com/v1".into(),
            api_key: "sk-ant-test".into(),
            model: "claude-3-7-sonnet".into(),
            custom_headers: None,
            custom_params: None,
            default_temperature: None,
            default_max_tokens: None,
            supports_thinking: true,
        }
    }

    fn full_request() -> AgentChatRequest {
        AgentChatRequest {
            turn_id: "01ARZ3NDEKTSV4RRFFQ69G5FAV".into(),
            thread_id: "t-1".into(),
            user_message: "hello".into(),
            provider_id: "anthropic".into(),
            model: "claude-3-7-sonnet".into(),
            workspace_path: Some("E:/work".into()),
            provider_config: minimal_provider_config(),
            system_prompt: Some("You are Aurora.".into()),
            ide_context: Some("<open_files>main.rs</open_files>".into()),
            tools: vec![AllowedTool {
                name: "file_read".into(),
                description: "Read a file".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": { "path": { "type": "string" } },
                    "required": ["path"],
                }),
            }],
            temperature: Some(0.7),
            max_output_tokens: Some(4096),
            thinking_enabled: Some(true),
            context_window: Some(200_000),
        }
    }

    #[test]
    fn agent_chat_request_round_trips_through_serde_json() {
        let req = full_request();
        let s = serde_json::to_string(&req).expect("serialize");
        let back: AgentChatRequest = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.turn_id, req.turn_id);
        assert_eq!(back.thread_id, req.thread_id);
        assert_eq!(back.user_message, req.user_message);
        assert_eq!(back.provider_id, req.provider_id);
        assert_eq!(back.model, req.model);
        assert_eq!(back.workspace_path, req.workspace_path);
        assert_eq!(back.provider_config.provider_id, "anthropic");
        assert_eq!(back.system_prompt.as_deref(), Some("You are Aurora."));
        assert_eq!(
            back.ide_context.as_deref(),
            Some("<open_files>main.rs</open_files>")
        );
        assert_eq!(back.tools.len(), 1);
        assert_eq!(back.tools[0].name, "file_read");
        assert_eq!(back.temperature, Some(0.7));
        assert_eq!(back.max_output_tokens, Some(4096));
        assert_eq!(back.thinking_enabled, Some(true));
    }

    #[test]
    fn agent_chat_request_emits_camelcase_keys() {
        let req = full_request();
        let s = serde_json::to_string(&req).expect("serialize");
        // Phase 2.3 contract: camelCase wire shape.
        assert!(s.contains("\"turnId\":"), "missing turnId, got: {s}");
        assert!(s.contains("\"threadId\":"), "missing threadId, got: {s}");
        assert!(
            s.contains("\"userMessage\":"),
            "missing userMessage, got: {s}"
        );
        assert!(
            s.contains("\"providerId\":"),
            "missing providerId, got: {s}"
        );
        assert!(
            s.contains("\"workspacePath\":"),
            "missing workspacePath, got: {s}"
        );
        assert!(
            s.contains("\"providerConfig\":"),
            "missing providerConfig, got: {s}"
        );
        assert!(
            s.contains("\"systemPrompt\":"),
            "missing systemPrompt, got: {s}"
        );
        assert!(
            s.contains("\"ideContext\":"),
            "missing ideContext, got: {s}"
        );
        assert!(s.contains("\"tools\":"), "missing tools, got: {s}");
        assert!(
            s.contains("\"maxOutputTokens\":"),
            "missing maxOutputTokens, got: {s}"
        );
        assert!(
            s.contains("\"thinkingEnabled\":"),
            "missing thinkingEnabled, got: {s}"
        );
        // Snake-case shape from Phase 2.2 must NOT leak through.
        assert!(
            !s.contains("\"turn_id\":"),
            "snake_case turn_id leaked, got: {s}"
        );
        assert!(
            !s.contains("\"user_message\":"),
            "snake_case user_message leaked, got: {s}"
        );
    }

    #[test]
    fn agent_chat_request_accepts_minimal_payload_with_defaults() {
        // Sub-B should be able to omit every #[serde(default)] field
        // and still get a valid request — only the six mandatory ones
        // (plus providerConfig) are required.
        let json = serde_json::json!({
            "turnId": "t-min",
            "threadId": "thread-min",
            "userMessage": "hi",
            "providerId": "anthropic",
            "model": "claude",
            "workspacePath": null,
            "providerConfig": {
                "providerId": "anthropic",
                "baseUrl": "https://api.anthropic.com/v1",
                "apiKey": "sk-ant",
                "model": "claude",
            },
        });
        let req: AgentChatRequest = serde_json::from_value(json).expect("deserialize minimal");
        assert_eq!(req.turn_id, "t-min");
        assert!(req.system_prompt.is_none());
        assert!(req.ide_context.is_none());
        assert!(req.tools.is_empty());
        assert!(req.temperature.is_none());
        assert!(req.max_output_tokens.is_none());
        assert!(req.thinking_enabled.is_none());
    }

    #[test]
    fn allowed_tool_round_trips_with_camelcase_keys() {
        let tool = AllowedTool {
            name: "shell_execute".into(),
            description: "Run a shell command".into(),
            parameters: serde_json::json!({
                "type": "object",
                "properties": { "command": { "type": "string" } },
            }),
        };
        let s = serde_json::to_string(&tool).expect("serialize");
        // No multi-word fields here so camelCase doesn't change
        // anything visible — but we still assert structural keys.
        assert!(s.contains("\"name\":\"shell_execute\""));
        assert!(s.contains("\"description\""));
        assert!(s.contains("\"parameters\""));
        let back: AllowedTool = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.name, "shell_execute");
        assert_eq!(back.parameters, tool.parameters);
    }

    #[test]
    fn agent_chat_request_emits_workspace_path_as_null_when_absent() {
        let req = AgentChatRequest {
            turn_id: "x".into(),
            thread_id: "t".into(),
            user_message: "u".into(),
            provider_id: "p".into(),
            model: "m".into(),
            workspace_path: None,
            provider_config: minimal_provider_config(),
            system_prompt: None,
            ide_context: None,
            tools: Vec::new(),
            temperature: None,
            max_output_tokens: None,
            thinking_enabled: None,
            context_window: None,
        };
        let s = serde_json::to_string(&req).expect("serialize");
        // Phase 2.3 contract: camelCase, no skip_serializing_if on
        // workspace_path, so the field appears as `null` for None.
        assert!(
            s.contains("\"workspacePath\":null"),
            "workspacePath None must serialize as null, got: {s}"
        );
    }

    #[test]
    fn envelope_carries_sequence_and_flattened_event() {
        let env = AgentEventEnvelope {
            turn_id: "t-99".into(),
            seq: 17,
            event: AssistantEvent::Usage(TokenUsage {
                input_tokens: 5,
                output_tokens: 9,
                cache_creation_input_tokens: None,
                cache_read_input_tokens: None,
            }),
        };
        let s = serde_json::to_string(&env).expect("serialize");
        // Envelope keeps snake_case for backwards-compat with the
        // already-shipped Phase 2.2 listener.
        assert!(s.contains("\"turn_id\":\"t-99\""), "got: {s}");
        assert!(s.contains("\"seq\":17"), "got: {s}");
        // Inner AssistantEvent::Usage stays internally tagged with
        // its own `"type"` key.
        assert!(s.contains("\"type\":\"usage\""), "got: {s}");
        assert!(s.contains("\"input_tokens\":5"), "got: {s}");
        assert!(s.contains("\"output_tokens\":9"), "got: {s}");
    }

    #[test]
    fn envelope_serializes_text_delta_event() {
        let env = AgentEventEnvelope {
            turn_id: "t-1".into(),
            seq: 0,
            event: AssistantEvent::TextDelta {
                delta: "hi".into(),
            },
        };
        let s = serde_json::to_string(&env).expect("serialize");
        assert!(s.contains("\"turn_id\":\"t-1\""));
        assert!(s.contains("\"seq\":0"));
        assert!(s.contains("\"type\":\"text_delta\""));
        assert!(s.contains("\"delta\":\"hi\""));
    }
}
