//! Tauri-facing wire types for the agent runtime IPC surface.
//!
//! Phase 2.3 extends the Phase 2.2 [`AgentChatRequest`] with the full
//! per-turn payload the frontend now sends:
//!
//! - [`crate::api::ProviderConfigSnapshot`] — opaque provider config
//!   passed straight through to the API factory.
//! - Pre-rendered system prompt (the frontend's
//!   `composeAgentSystemPrompt(...)` already does this composition; the
//!   runtime never composes prompts itself).
//! - Optional context block for this message — saved on the user
//!   message as its `aurora_context` and read by the model after the
//!   user's words, while the persisted bubble keeps the clean
//!   `user_message`.
//! - Tool catalogue (each entry's JSON-Schema parameters) — every name
//!   in this list resolves to a [`crate::agent_runtime::bridge::FrontendBridgeExecutor`]
//!   in the per-turn registry.
//! - Sampling temperature, max output tokens, thinking flag — per-turn
//!   overrides over the defaults baked into [`crate::agent_runtime::conversation::RuntimeConfig`].
//!
//! Wire format: `#[serde(rename_all = "camelCase")]`. The frontend
//! sends `{ "turnId": "...", "providerConfig": {...},
//! "systemPrompt": "...", "ideContext": "...", "tools": [...],
//! "temperature": 0.7, "maxOutputTokens": 4096,
//! "thinkingEnabled": true }`. This is a deliberate change from the
//! Phase 2.2 snake_case shape — `agent_chat_v2` is brand-new IPC and
//! nothing in the live frontend depends on the old shape.
//!
//! [`AgentEventEnvelope`] keeps the Phase 2.2 snake_case shape because
//! the streaming envelope already shipped with that format and the
//! frontend's Phase 2.2 listener stayed compatible with that side of
//! the contract.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

use super::events::AssistantEvent;
use super::types::{AttachedPromptChip, AttachedSelectedElement};

/// Runtime-enforced tool authority for one turn.
///
/// The first three work on a project. [`Chat`](Self::Chat) does not: it is the
/// separate product surface (Aurora Chat), with its own conversation store under
/// `paths::chats_dir()`, its own system prompt, and a tool roster that is NAMED
/// rather than subtracted — see `commands::agent_v2::tool_policy`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AgentExecutionMode {
    #[default]
    Agent,
    Plan,
    Team,
    /// Aurora Chat. No files, no shell, no workspace.
    ///
    /// Deliberately a variant of THIS enum rather than a parallel flag: the
    /// per-turn tool gate already keys on execution mode, and a second
    /// dimension would mean every call site asking two questions where one
    /// would do. What makes it different from its siblings is not enforced
    /// here but at the two places that matter — the roster in
    /// `is_tool_available_this_turn`, and which session store the turn writes
    /// to.
    Chat,
}

impl AgentExecutionMode {
    /// Is this the chat product rather than one of the three project modes?
    ///
    /// Named rather than compared inline so a call site reads as what it is
    /// asking. Every `== Chat` in the codebase should be this instead.
    #[must_use]
    pub fn is_chat(self) -> bool {
        matches!(self, Self::Chat)
    }

    /// Does this mode operate on a workspace at all?
    ///
    /// The three project modes do. Chat does not, and a turn that answers
    /// `false` here must never be handed a `workspace_root`, because the file
    /// tools treat `None` as "no boundary" rather than "no access" — see the
    /// note in `tools::file_workspace_search::resolve_path_with_access`.
    #[must_use]
    pub fn has_workspace(self) -> bool {
        !self.is_chat()
    }
}

impl AgentChatRequest {
    /// Drop a workspace path a chat turn should never have carried.
    ///
    /// Applied ONCE, where the request enters the driver, rather than guarded
    /// at each of the eleven places that read `workspace_path`. A guard per
    /// call site is a guard somebody forgets to add to the twelfth.
    ///
    /// It matters for more than the file tools, which chat mode does not have
    /// anyway. `workspace_root` is also what scopes a conversation to a
    /// project: it is written to the thread's metadata sidecar, and
    /// `SessionStore::list_summaries_filtered` uses it to decide which chats
    /// are visible. A chat that acquired one would vanish from the chat list
    /// the moment the rail asked for conversations belonging to no project.
    #[must_use]
    pub fn scoped_to_mode(mut self) -> Self {
        if !self.execution_mode.has_workspace() {
            self.workspace_path = None;
        }
        self
    }
}

/// Frontend → backend request to start one agent turn.
///
/// `turn_id` is a ULID generated by the frontend so it can correlate
/// the streamed [`AgentEventEnvelope`]s with the originating call
/// without an extra round trip. The frontend treats the envelope
/// stream as the authoritative ordering — `turn_id` is the join key.
///
/// Wire format: `rename_all = "camelCase"`. See module docs for the
/// JSON shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentChatRequest {
    // ── Phase 2.2 fields ───────────────────────────────────────────
    /// ULID generated client-side. Used as the event-channel
    /// correlation id and the bridge oneshot key.
    pub turn_id: String,
    /// Identifier of the chat thread this turn belongs to. Maps to the
    /// JSONL log under `<agent_root>/agent_v2/{thread_id}.jsonl`.
    pub thread_id: String,
    /// Raw user input. The runtime persists this verbatim into the
    /// session JSONL; `ide_context` (see below) is saved beside it and
    /// folded in after it on every API request.
    pub user_message: String,
    /// Who is starting this turn.
    ///
    /// Defaults to the user, which is every send a person makes. `Process`
    /// means a background process ended while nothing was running and Aurora
    /// woke the conversation to say so — the message is real and the model must
    /// answer it, but nobody typed it, so it is persisted as a
    /// [`crate::agent_runtime::types::ContentBlock::ProcessEvent`] and the
    /// transcript draws a beat rather than a bubble.
    ///
    /// Defaulted rather than required: every existing caller sends a person's
    /// words, and a missing field must never silently strip attribution from
    /// one.
    #[serde(default)]
    pub user_message_origin: crate::agent_runtime::types::InjectedOrigin,
    /// The one line the transcript draws when [`Self::user_message_origin`] is
    /// `Process`, where [`Self::user_message`] is what the model reads.
    ///
    /// The split is the same one the mid-turn injection makes: "Finished pnpm
    /// test · exit 1" is what a person needs; the model needs the process id
    /// and the log path, because its useful next move is `shell_read_output`
    /// and it cannot make that call out of prose. Ignored for a user message,
    /// whose bubble shows the words that were typed.
    #[serde(default)]
    pub user_message_summary: Option<String>,
    /// LLM provider identifier. Used by the
    /// [`crate::commands::agent_v2::AgentRegistry`] for telemetry; the
    /// real provider routing is done by the [`provider_config`] field
    /// below (which carries its own `provider_id`).
    pub provider_id: String,
    /// Model name to send to the provider (e.g.
    /// `"claude-3-7-sonnet-20250219"`). Echoed by the runtime into the
    /// session log on the first turn for telemetry.
    pub model: String,
    /// The model as the **conversation** is pinned to it, when that differs
    /// from what goes on the wire.
    ///
    /// Cursor is the one provider where they differ. Its effort tier and its
    /// Fast lane are capabilities the user picks, not part of what the model
    /// is — so the row, the picker and this pin all hold `cursor-grok-4.6`,
    /// while the request carries the id those choices compose to,
    /// `cursor-grok-4.6-high-fast`.
    ///
    /// Recording the composed id as the pin is what this exists to prevent.
    /// The pin is the key every later lookup uses, so a decorated one matches
    /// no model row: the model's real context window becomes unfindable and
    /// the turn is budgeted against the provider default instead.
    ///
    /// `None` — every other provider — means the wire model *is* the pin.
    #[serde(default)]
    pub model_selection: Option<String>,
    /// Optional workspace root. Tools that touch the filesystem
    /// resolve paths against this root.
    pub workspace_path: Option<String>,

    /// Authoritative execution mode. Unlike the system-prompt description,
    /// this value is enforced when Rust builds the per-turn tool registry.
    #[serde(default)]
    pub execution_mode: AgentExecutionMode,

    /// The `aurora agent` task this turn is running, when it came from one.
    ///
    /// Set only for a turn the Agent Window started on behalf of a terminal
    /// dispatch. The runtime uses it to tee this turn's events into the task's
    /// transcript (see [`crate::cli_delegate::mirror`]) so `aurora agent
    /// --follow` can watch the same work the window is showing.
    ///
    /// Carried on the request rather than bound by the frontend because the
    /// binding needs a `turn_id`, and the turn id is generated *inside* the
    /// runtime client — reaching it from the window would mean threading it
    /// back out through every callback in the chain to serve one caller.
    #[serde(default)]
    pub cli_task_id: Option<String>,

    // ── Phase 2.3 NEW fields ───────────────────────────────────────
    /// Full provider configuration snapshot (api_key, base_url,
    /// custom_headers, custom_params, …). Sent verbatim from the
    /// frontend's `useSettingsStore.getLLMConfig()`. The runtime
    /// passes it unchanged to [`crate::api::build_api_client`]; the
    /// adapters are the only code that interprets the inner fields.
    pub provider_config: crate::api::ProviderConfigSnapshot,

    /// Pre-rendered system prompt. Built by the frontend's existing
    /// `composeAgentSystemPrompt(...)` machinery — the runtime never
    /// composes system prompts itself.
    #[serde(default)]
    pub system_prompt: Option<String>,

    /// What the frontend attached to THIS message for the model: the files
    /// open in the dock, a selection, a slash-attached rule, an MCP
    /// directive. Facts about the message, not about the conversation —
    /// project rules, the skill catalogue and the execution mode belong in
    /// `system_prompt`, where the frontend already composes them.
    ///
    /// Saved on the user message as `ConversationMessage::aurora_context`
    /// (the runtime adds the checklist as it stands), and never rebuilt: the
    /// model reads it after the user's words on every request, the bubble
    /// shows the words alone.
    #[serde(default)]
    pub ide_context: Option<String>,

    /// Tool catalogue advertised to the model. Each entry's
    /// `parameters` is a JSON-Schema object describing the tool's
    /// input. Phase 2.3 forwards every tool name through the
    /// `FrontendBridgeExecutor` (see `crate::agent_runtime::bridge`)
    /// — the Rust tool registry stays empty until Phase 3 ports the
    /// native executors.
    #[serde(default)]
    pub tools: Vec<AllowedTool>,

    /// Sampling temperature. `None` defers to the provider preset
    /// default (some, like DeepSeek's reasoner, ignore it entirely).
    #[serde(default)]
    pub temperature: Option<f32>,

    /// Hard cap per API call. `None` defers to
    /// [`crate::agent_runtime::conversation::RuntimeConfig::default_max_output_tokens`].
    #[serde(default)]
    pub max_output_tokens: Option<u32>,

    /// Whether to enable extended thinking. Honoured only when the
    /// provider preset advertises thinking support; the impl silently
    /// drops it otherwise. `None` means "use the default" (`false`).
    #[serde(default)]
    pub thinking_enabled: Option<bool>,

    /// Explicit thinking token budget, in tokens, for models whose reasoning
    /// control is a budget rather than an effort tier (the composer's model
    /// picker writes it per model). Read only when [`Self::thinking_enabled`]
    /// is true — a budget never turns thinking on by itself.
    ///
    /// `None`/`0` means "no explicit budget": the Anthropic adapter then falls
    /// back to scaling the effort tier against `max_output_tokens`, and the
    /// OpenAI-compatible adapter omits the field entirely (many compat
    /// backends reject unknown keys with HTTP 400).
    #[serde(default)]
    pub thinking_budget_tokens: Option<u32>,

    /// Provider's advertised total context window (input + output) for
    /// the chosen model, in tokens. When set, the runtime applies a
    /// budget-aware trim before each API call: older turns get dropped
    /// (from oldest first, always preserving the last two user-anchored
    /// turns) once the persisted session would exceed ~75% of
    /// `(context_window - max_output_tokens * 1.1)`. The persisted JSONL
    /// is untouched — only the API view is trimmed.
    ///
    /// `None` disables trimming entirely. Callers that don't pass a
    /// window get the legacy behaviour (whole session sent every turn).
    #[serde(default)]
    pub context_window: Option<u32>,

    /// Compaction trigger as a percentage of `context_window` (e.g. `80`).
    /// When the projected request crosses it, the runtime summarizes older
    /// history into a persistent marker before continuing (see
    /// `DOCS/compaction-design.md`). `None`/`0` disables compaction — the
    /// request then relies on `trim` alone. User-configurable (Settings →
    /// Agent), clamped 50–95 on the frontend.
    #[serde(default)]
    pub compaction_threshold_pct: Option<f32>,

    /// `max_output_tokens` budget for the summarization call. `None` uses the
    /// runtime default (8192). User-configurable (Settings → Agent), clamped
    /// 2,000–16,000 on the frontend.
    #[serde(default)]
    pub compaction_summary_budget: Option<u32>,

    /// Provider the summarization call runs on, when the user pinned one
    /// (Settings → Agent → Compaction model). `None` summarizes on the
    /// conversation's own provider — the prior, and still default, behaviour.
    ///
    /// A full config snapshot rather than a model name because the runtime
    /// builds a second API client from it: the summarizer must be able to
    /// reach a provider the chat is not using, with its own key and base URL.
    #[serde(default)]
    pub compaction_provider_config: Option<crate::api::ProviderConfigSnapshot>,

    /// How far outside the project this turn's file tools may reach:
    /// `"workspace"`, `"read"`, or `"full"` (user choice, Settings → Tools).
    /// Absent or unrecognised keeps the strict workspace boundary.
    #[serde(default)]
    pub workspace_access: Option<String>,

    /// The boolean this setting used to be, still accepted on the wire.
    ///
    /// An install that upgrades without opening Settings sends only this, and
    /// dropping it would silently re-fence an agent the user had already let
    /// out. `true` maps to `"read"` — never to `"full"`, which nobody has
    /// consented to. Read only when [`Self::workspace_access`] is absent; see
    /// `WorkspaceAccess::from_wire`.
    #[serde(default)]
    pub allow_outside_workspace: Option<bool>,

    /// When true, the model is advertised the `chapter` tool so it can name the
    /// parts of a long turn (user opt-in, Settings → Preferences → Transcript).
    /// Sent per turn from the same preference read that decides whether the
    /// chapter instruction goes into the system prompt, so the roster and the
    /// instruction can never disagree. `None`/`false` withholds the tool.
    #[serde(default)]
    pub transcript_chapters: Option<bool>,

    /// Browser access this turn (Settings → Agent → Browser control).
    /// Available browser tools use discovery; false removes the whole bucket.
    /// `None` preserves the enabled default for older clients.
    #[serde(default)]
    pub browser_tools: Option<bool>,

    /// Legacy preference, accepted for saved settings and older clients.
    /// Optional tools always use tool_search and call_tool; this value is inert.
    #[serde(default)]
    pub defer_tools: Option<bool>,

    /// Browser-inspector element chips the user attached to this message
    /// in the composer. Persisted verbatim onto the user
    /// [`crate::agent_runtime::types::ConversationMessage`] so the chips
    /// survive thread reopen. Display-only — the full element context
    /// reaches the model through `ide_context`. `None`/empty when the
    /// user attached nothing.
    #[serde(default)]
    pub attached_selected_elements: Option<Vec<AttachedSelectedElement>>,

    /// Exact file and `/` pills attached in the composer. Display-only and
    /// persisted with the user message so thread reloads remain faithful.
    #[serde(default)]
    pub attached_prompt_chips: Option<Vec<AttachedPromptChip>>,

    /// The image providers `generate_image` may use this turn — the rows from
    /// Settings → Providers → Image providers, keys included, sent by the
    /// frontend on every Aurora Chat turn and ignored in the project modes.
    ///
    /// Sent per turn rather than stored in Rust so a provider added
    /// mid-conversation is usable from the next message, the same way the
    /// conversation's own `provider_config` is. The turn driver parks them in
    /// `tools::image::config` keyed by conversation before the turn runs.
    #[serde(default)]
    pub image_providers: Vec<crate::tools::image::config::ImageProviderConfig>,
}

/// One tool entry in [`AgentChatRequest::tools`].
///
/// Maps onto Aurora's TypeScript `ToolDefinition` shape: `name`,
/// `description`, and a JSON-Schema `parameters` object the runtime
/// hands to the model verbatim. The bridge dispatches calls of this
/// name back to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllowedTool {
    pub name: String,
    pub description: String,
    /// JSON Schema object describing the tool's input.
    pub parameters: serde_json::Value,
}

/// Backend → frontend event envelope.
///
/// `seq` is monotonic per `turn_id`, starting at 0 with the first
/// event of a turn. The frontend uses it to detect dropped or out-of-
/// order events; in correct operation it always increments by 1.
///
/// `Serialize`-only because envelopes flow strictly Rust → frontend.
/// Wire format keeps the Phase 2.2 snake_case shape.
#[derive(Debug, Clone, Serialize)]
pub struct AgentEventEnvelope {
    pub turn_id: String,
    pub seq: u64,
    pub event: AssistantEvent,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent_runtime::types::TokenUsage;
    use crate::api::ProviderConfigSnapshot;

    fn minimal_provider_config() -> ProviderConfigSnapshot {
        ProviderConfigSnapshot {
            provider_id: "anthropic".into(),
            provider_type: None,
            base_url: "https://api.anthropic.com/v1".into(),
            api_key: "sk-ant-test".into(),
            api_keys: None,
            model: "claude-3-7-sonnet".into(),
            custom_headers: None,
            custom_params: None,
            default_temperature: None,
            default_max_tokens: None,
            supports_thinking: true,
            reasoning: None,
            supports_vision: false,
        }
    }

    fn full_request() -> AgentChatRequest {
        AgentChatRequest {
            cli_task_id: None,
            turn_id: "01ARZ3NDEKTSV4RRFFQ69G5FAV".into(),
            thread_id: "t-1".into(),
            user_message: "hello".into(),
            user_message_origin: crate::agent_runtime::types::InjectedOrigin::User,
            user_message_summary: None,
            provider_id: "anthropic".into(),
            model: "claude-3-7-sonnet".into(),
            model_selection: None,
            workspace_path: Some("E:/work".into()),
            execution_mode: AgentExecutionMode::Agent,
            provider_config: minimal_provider_config(),
            system_prompt: Some("You are Aurora.".into()),
            ide_context: Some("<open_files>main.rs</open_files>".into()),
            tools: vec![AllowedTool {
                name: "file_read".into(),
                description: "Read a file".into(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": { "path": { "type": "string" } },
                    "required": ["path"],
                }),
            }],
            temperature: Some(0.7),
            max_output_tokens: Some(4096),
            thinking_enabled: Some(true),
            thinking_budget_tokens: Some(16_000),
            context_window: Some(200_000),
            attached_selected_elements: None,
            attached_prompt_chips: None,
            image_providers: Vec::new(),
            compaction_threshold_pct: None,
            compaction_summary_budget: None,
            compaction_provider_config: None,
            workspace_access: None,
            allow_outside_workspace: None,
            transcript_chapters: None,
            browser_tools: None,
            defer_tools: None,
        }
    }

    #[test]
    fn agent_chat_request_round_trips_through_serde_json() {
        let req = full_request();
        let s = serde_json::to_string(&req).expect("serialize");
        let back: AgentChatRequest = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.turn_id, req.turn_id);
        assert_eq!(back.thread_id, req.thread_id);
        assert_eq!(back.user_message, req.user_message);
        assert_eq!(back.provider_id, req.provider_id);
        assert_eq!(back.model, req.model);
        assert_eq!(back.workspace_path, req.workspace_path);
        assert_eq!(back.execution_mode, AgentExecutionMode::Agent);
        assert_eq!(back.provider_config.provider_id, "anthropic");
        assert_eq!(back.system_prompt.as_deref(), Some("You are Aurora."));
        assert_eq!(
            back.ide_context.as_deref(),
            Some("<open_files>main.rs</open_files>")
        );
        assert_eq!(back.tools.len(), 1);
        assert_eq!(back.tools[0].name, "file_read");
        assert_eq!(back.temperature, Some(0.7));
        assert_eq!(back.max_output_tokens, Some(4096));
        assert_eq!(back.thinking_enabled, Some(true));
    }

    #[test]
    fn agent_chat_request_emits_camelcase_keys() {
        let req = full_request();
        let s = serde_json::to_string(&req).expect("serialize");
        // Phase 2.3 contract: camelCase wire shape.
        assert!(s.contains("\"turnId\":"), "missing turnId, got: {s}");
        assert!(s.contains("\"threadId\":"), "missing threadId, got: {s}");
        assert!(
            s.contains("\"userMessage\":"),
            "missing userMessage, got: {s}"
        );
        assert!(
            s.contains("\"providerId\":"),
            "missing providerId, got: {s}"
        );
        assert!(
            s.contains("\"workspacePath\":"),
            "missing workspacePath, got: {s}"
        );
        assert!(
            s.contains("\"executionMode\":\"agent\""),
            "missing executionMode, got: {s}"
        );
        assert!(
            s.contains("\"providerConfig\":"),
            "missing providerConfig, got: {s}"
        );
        assert!(
            s.contains("\"systemPrompt\":"),
            "missing systemPrompt, got: {s}"
        );
        assert!(
            s.contains("\"ideContext\":"),
            "missing ideContext, got: {s}"
        );
        assert!(s.contains("\"tools\":"), "missing tools, got: {s}");
        assert!(
            s.contains("\"maxOutputTokens\":"),
            "missing maxOutputTokens, got: {s}"
        );
        assert!(
            s.contains("\"thinkingEnabled\":"),
            "missing thinkingEnabled, got: {s}"
        );
        // Snake-case shape from Phase 2.2 must NOT leak through.
        assert!(
            !s.contains("\"turn_id\":"),
            "snake_case turn_id leaked, got: {s}"
        );
        assert!(
            !s.contains("\"user_message\":"),
            "snake_case user_message leaked, got: {s}"
        );
    }

    #[test]
    fn agent_chat_request_accepts_minimal_payload_with_defaults() {
        // Sub-B should be able to omit every #[serde(default)] field
        // and still get a valid request — only the six mandatory ones
        // (plus providerConfig) are required.
        let json = serde_json::json!({
            "turnId": "t-min",
            "threadId": "thread-min",
            "userMessage": "hi",
            "providerId": "anthropic",
            "model": "claude",
            "workspacePath": null,
            "providerConfig": {
                "providerId": "anthropic",
                "baseUrl": "https://api.anthropic.com/v1",
                "apiKey": "sk-ant",
                "model": "claude",
            },
        });
        let req: AgentChatRequest = serde_json::from_value(json).expect("deserialize minimal");
        assert_eq!(req.turn_id, "t-min");
        assert!(req.system_prompt.is_none());
        assert!(req.ide_context.is_none());
        assert!(req.tools.is_empty());
        assert!(req.temperature.is_none());
        assert!(req.max_output_tokens.is_none());
        assert!(req.thinking_enabled.is_none());
        assert_eq!(req.execution_mode, AgentExecutionMode::Agent);
    }

    #[test]
    fn allowed_tool_round_trips_with_camelcase_keys() {
        let tool = AllowedTool {
            name: "shell_execute".into(),
            description: "Run a shell command".into(),
            parameters: serde_json::json!({
                "type": "object",
                "properties": { "command": { "type": "string" } },
            }),
        };
        let s = serde_json::to_string(&tool).expect("serialize");
        // No multi-word fields here so camelCase doesn't change
        // anything visible — but we still assert structural keys.
        assert!(s.contains("\"name\":\"shell_execute\""));
        assert!(s.contains("\"description\""));
        assert!(s.contains("\"parameters\""));
        let back: AllowedTool = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.name, "shell_execute");
        assert_eq!(back.parameters, tool.parameters);
    }

    #[test]
    fn agent_chat_request_emits_workspace_path_as_null_when_absent() {
        let req = AgentChatRequest {
            cli_task_id: None,
            turn_id: "x".into(),
            thread_id: "t".into(),
            user_message: "u".into(),
            user_message_origin: crate::agent_runtime::types::InjectedOrigin::User,
            user_message_summary: None,
            provider_id: "p".into(),
            model: "m".into(),
            model_selection: None,
            workspace_path: None,
            execution_mode: AgentExecutionMode::Agent,
            provider_config: minimal_provider_config(),
            system_prompt: None,
            ide_context: None,
            tools: Vec::new(),
            temperature: None,
            max_output_tokens: None,
            thinking_enabled: None,
            thinking_budget_tokens: None,
            context_window: None,
            attached_selected_elements: None,
            attached_prompt_chips: None,
            image_providers: Vec::new(),
            compaction_threshold_pct: None,
            compaction_summary_budget: None,
            compaction_provider_config: None,
            workspace_access: None,
            allow_outside_workspace: None,
            transcript_chapters: None,
            browser_tools: None,
            defer_tools: None,
        };
        let s = serde_json::to_string(&req).expect("serialize");
        // Phase 2.3 contract: camelCase, no skip_serializing_if on
        // workspace_path, so the field appears as `null` for None.
        assert!(
            s.contains("\"workspacePath\":null"),
            "workspacePath None must serialize as null, got: {s}"
        );
    }

    #[test]
    fn envelope_carries_sequence_and_flattened_event() {
        let env = AgentEventEnvelope {
            turn_id: "t-99".into(),
            seq: 17,
            event: AssistantEvent::Usage(TokenUsage {
                input_tokens: 5,
                output_tokens: 9,
                cache_creation_input_tokens: None,
                cache_read_input_tokens: None,
                estimated: None,
                cost_usd: None,
            }),
        };
        let s = serde_json::to_string(&env).expect("serialize");
        // Envelope keeps snake_case for backwards-compat with the
        // already-shipped Phase 2.2 listener.
        assert!(s.contains("\"turn_id\":\"t-99\""), "got: {s}");
        assert!(s.contains("\"seq\":17"), "got: {s}");
        // Inner AssistantEvent::Usage stays internally tagged with
        // its own `"type"` key.
        assert!(s.contains("\"type\":\"usage\""), "got: {s}");
        assert!(s.contains("\"input_tokens\":5"), "got: {s}");
        assert!(s.contains("\"output_tokens\":9"), "got: {s}");
    }

    #[test]
    fn envelope_serializes_text_delta_event() {
        let env = AgentEventEnvelope {
            turn_id: "t-1".into(),
            seq: 0,
            event: AssistantEvent::TextDelta { delta: "hi".into() },
        };
        let s = serde_json::to_string(&env).expect("serialize");
        assert!(s.contains("\"turn_id\":\"t-1\""));
        assert!(s.contains("\"seq\":0"));
        assert!(s.contains("\"type\":\"text_delta\""));
        assert!(s.contains("\"delta\":\"hi\""));
    }
}
