//! Tauri commands for the Phase 4 permission prompter.
//!
//! Surfaces a single command — `agent_grant_permission` — that the
//! frontend modal calls once the user clicks Allow / Deny on a
//! pending permission prompt. The command resolves the matching
//! `oneshot::Sender<bool>` parked on
//! [`crate::tools::permissions::PermissionRouter`].
//!
//! Mirrors the structure of [`crate::commands::agent_v2`]'s
//! `tauri_layer` mod — a `verify_only`-gated module that holds the
//! Tauri-specific bits, plus a glob `pub use` so
//! `tauri::generate_handler!` can pick the command up by its short
//! name (`commands::agent_v2_permissions::agent_grant_permission`).
//!
//! Sub-E (or the parent agent's final-10% step) registers the
//! `Arc<PermissionRouter>` into Tauri's
//! [`tauri::Manager::manage`] state alongside the existing
//! `Arc<AgentRegistry>`, so the command can resolve it via
//! [`tauri::State`].
//!
//! ## Wiring summary (parent agent's reference)
//!
//! ```ignore
//! // inside lib.rs::run()
//! let perm_router = Arc::new(PermissionRouter::new());
//! let perm_emitter: Arc<dyn PermissionEmitter> =
//!     Arc::new(MyTauriPermissionEmitter::new(app.handle().clone()));
//! let permitter = Arc::new(TauriPermitter::new(perm_router.clone(), perm_emitter));
//! tool_registry = tool_registry.with_permitter(permitter);
//! app.manage(perm_router);
//! ```
//!
//! Then `tauri::generate_handler!` includes
//! `commands::agent_v2_permissions::agent_grant_permission`.

#![allow(dead_code)]

// ============================================================================
// Tauri layer — production glue. Excluded from the verify crate via the
// "verify_only" feature so the standalone test crate stays Tauri-free.
// ============================================================================

#[cfg(not(feature = "verify_only"))]
mod tauri_layer {
    use std::sync::Arc;

    use tauri::State;

    use crate::tools::permissions::PermissionRouter;

    /// Resolve a pending permission prompt with the user's verdict.
    ///
    /// `granted: true` allows the tool to proceed; `false` raises
    /// [`crate::agent_runtime::tool_executor::ToolError::PermissionDenied`].
    ///
    /// Returns `Ok(())` when a pending oneshot was found and resolved.
    /// Returns `Err("no pending permission request")` when nothing
    /// matched the `(turn_id, tool_name)` pair (the request was
    /// cancelled, the turn already finished, or the frontend
    /// duplicated the post). The wording mirrors
    /// [`crate::commands::agent_v2::agent_post_tool_result`].
    #[tauri::command]
    pub async fn agent_grant_permission(
        router: State<'_, Arc<PermissionRouter>>,
        turn_id: String,
        tool_name: String,
        granted: bool,
    ) -> Result<(), String> {
        match router.inner().resolve(&turn_id, &tool_name, granted) {
            Ok(()) => Ok(()),
            Err(_returned) => Err("no pending permission request".to_string()),
        }
    }
}

// Glob re-export so the `__cmd__*` companion modules generated by
// `#[tauri::command]` are visible to `tauri::generate_handler!` at the
// `commands::agent_v2_permissions::agent_grant_permission` path.
#[cfg(not(feature = "verify_only"))]
pub use tauri_layer::*;

// ============================================================================
// Verify-friendly façade — same logic, no Tauri dependency. Exercised
// by the standalone __verify_phase3_d crate.
// ============================================================================

/// Verify-friendly version of `agent_grant_permission`. Mirrors the
/// production command's behaviour 1:1; the Tauri layer simply
/// extracts the router out of `State<>` before delegating to this
/// function.
///
/// Public because the verify crate calls it; production callers go
/// through the `#[tauri::command]` above.
pub fn resolve_permission(
    router: &crate::tools::permissions::PermissionRouter,
    turn_id: &str,
    tool_name: &str,
    granted: bool,
) -> Result<(), String> {
    match router.resolve(turn_id, tool_name, granted) {
        Ok(()) => Ok(()),
        Err(_returned) => Err("no pending permission request".to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tools::permissions::PermissionRouter;

    #[test]
    fn resolve_permission_succeeds_when_pending() {
        let router = PermissionRouter::new();
        let mut rx = router.register("turn-1".into(), "shell_execute".into());
        resolve_permission(&router, "turn-1", "shell_execute", true).expect("ok");
        assert_eq!(rx.try_recv().expect("ok"), true);
    }

    #[test]
    fn resolve_permission_errors_when_unknown() {
        let router = PermissionRouter::new();
        let err = resolve_permission(&router, "missing", "shell_execute", true)
            .expect_err("must fail");
        assert_eq!(err, "no pending permission request");
    }

    #[test]
    fn resolve_permission_returns_deny_when_pending() {
        let router = PermissionRouter::new();
        let mut rx = router.register("turn-2".into(), "shell_execute".into());
        resolve_permission(&router, "turn-2", "shell_execute", false).expect("ok");
        assert_eq!(rx.try_recv().expect("ok"), false);
    }
}
