use serde::Serialize;
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderCatalogPreset {
    pub id: String,
    pub name: String,
    pub nickname: Option<String>,
    pub base_url: String,
    pub model: String,
    pub context_window: u32,
    pub max_output_tokens: u32,
    pub supports_thinking: bool,
    pub supports_tool_stream: Option<bool>,
    pub custom_models: Option<Vec<String>>,
    pub model_aliases: Option<HashMap<String, String>>,
    pub provider_type: String,
    pub default_temperature: Option<f32>,
    pub default_max_tokens: Option<u32>,
    pub requires_api_key: bool,
}

pub fn built_in_provider_presets() -> Vec<ProviderCatalogPreset> {
    vec![
        ProviderCatalogPreset {
            id: "fireworks".to_string(),
            name: "Fireworks AI".to_string(),
            nickname: Some("Fireworks".to_string()),
            base_url: "https://api.fireworks.ai/inference/v1".to_string(),
            model: "accounts/fireworks/models/kimi-k2-instruct-0905".to_string(),
            context_window: 200000,
            max_output_tokens: 32768,
            supports_thinking: true,
            supports_tool_stream: None,
            custom_models: Some(vec![
                "accounts/fireworks/models/kimi-k2-instruct-0905".to_string(),
                "accounts/fireworks/models/kimi-k2-thinking".to_string(),
                "accounts/fireworks/models/kimi-k2p5".to_string(),
                "accounts/fireworks/models/deepseek-v3p2".to_string(),
                "accounts/fireworks/models/glm-5".to_string(),
                "accounts/fireworks/models/qwen2p5-coder-32b-instruct".to_string(),
            ]),
            model_aliases: Some(HashMap::from([
                (
                    "accounts/fireworks/models/deepseek-v3p2".to_string(),
                    "DeepSeek V3.2".to_string(),
                ),
                (
                    "accounts/fireworks/models/glm-5".to_string(),
                    "GLM 5".to_string(),
                ),
                (
                    "accounts/fireworks/models/kimi-k2-instruct-0905".to_string(),
                    "Kimi K2".to_string(),
                ),
                (
                    "accounts/fireworks/models/kimi-k2-thinking".to_string(),
                    "Kimi K2 Thinking".to_string(),
                ),
                (
                    "accounts/fireworks/models/kimi-k2p5".to_string(),
                    "Kimi K2.5".to_string(),
                ),
                (
                    "accounts/fireworks/models/qwen2p5-coder-32b-instruct".to_string(),
                    "Qwen 2.5 Coder 32B".to_string(),
                ),
            ])),
            provider_type: "fireworks".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "glm".to_string(),
            name: "GLM-4.7 (Z.AI)".to_string(),
            nickname: Some("GLM".to_string()),
            base_url: "https://api.z.ai/api/coding/paas/v4".to_string(),
            model: "glm-4.7".to_string(),
            context_window: 200000,
            max_output_tokens: 128000,
            supports_thinking: true,
            supports_tool_stream: None,
            custom_models: Some(vec![
                "glm-4.7".to_string(),
                "glm-4.6".to_string(),
                "glm-4.5".to_string(),
                "glm-4.5-flash".to_string(),
            ]),
            model_aliases: None,
            provider_type: "glm".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "anthropic".to_string(),
            name: "Anthropic".to_string(),
            nickname: Some("Claude".to_string()),
            base_url: "https://api.anthropic.com/v1".to_string(),
            model: "claude-sonnet-4-20250514".to_string(),
            context_window: 200000,
            max_output_tokens: 8192,
            supports_thinking: true,
            supports_tool_stream: None,
            custom_models: Some(vec![
                "claude-opus-4-5-20251101".to_string(),
                "claude-sonnet-4-20250514".to_string(),
                "claude-3-5-sonnet-20241022".to_string(),
                "claude-3-5-haiku-20241022".to_string(),
            ]),
            model_aliases: None,
            provider_type: "anthropic".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "minimax".to_string(),
            name: "MiniMax M2.1".to_string(),
            nickname: Some("MiniMax".to_string()),
            base_url: "https://api.minimax.io/anthropic/v1".to_string(),
            model: "MiniMax-M2.1".to_string(),
            context_window: 200000,
            max_output_tokens: 128000,
            supports_thinking: true,
            supports_tool_stream: None,
            custom_models: Some(vec!["MiniMax-M2.1".to_string()]),
            model_aliases: None,
            provider_type: "anthropic".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "deepseek".to_string(),
            name: "DeepSeek".to_string(),
            nickname: None,
            base_url: "https://api.deepseek.com/v1".to_string(),
            model: "deepseek-chat".to_string(),
            context_window: 64000,
            max_output_tokens: 64000,
            supports_thinking: true,
            supports_tool_stream: None,
            custom_models: Some(vec![
                "deepseek-chat".to_string(),
                "deepseek-reasoner".to_string(),
            ]),
            model_aliases: None,
            provider_type: "deepseek".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "openai".to_string(),
            name: "OpenAI".to_string(),
            nickname: None,
            base_url: "https://api.openai.com/v1".to_string(),
            model: "gpt-4o".to_string(),
            context_window: 128000,
            max_output_tokens: 16384,
            supports_thinking: false,
            supports_tool_stream: None,
            custom_models: Some(vec![
                "gpt-4o".to_string(),
                "gpt-4o-mini".to_string(),
                "gpt-4-turbo".to_string(),
                "gpt-3.5-turbo".to_string(),
                "o1".to_string(),
                "o1-mini".to_string(),
            ]),
            model_aliases: None,
            provider_type: "openai".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: true,
        },
        ProviderCatalogPreset {
            id: "lmstudio".to_string(),
            name: "LM Studio".to_string(),
            nickname: None,
            base_url: "http://localhost:1234/v1".to_string(),
            model: "local-model".to_string(),
            context_window: 128000,
            max_output_tokens: 8192,
            supports_thinking: false,
            supports_tool_stream: None,
            custom_models: Some(Vec::new()),
            model_aliases: None,
            provider_type: "lmstudio".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: false,
        },
        ProviderCatalogPreset {
            id: "ollama".to_string(),
            name: "Ollama".to_string(),
            nickname: None,
            base_url: "http://localhost:11434/v1".to_string(),
            model: "llama3".to_string(),
            context_window: 128000,
            max_output_tokens: 8192,
            supports_thinking: false,
            supports_tool_stream: None,
            custom_models: Some(Vec::new()),
            model_aliases: None,
            provider_type: "ollama".to_string(),
            default_temperature: Some(1.0),
            default_max_tokens: None,
            requires_api_key: false,
        },
    ]
}
