//! The Tauri commands the Agent Window uses to run a dispatched task.
//!
//! The window receives a claimed task on the `cli-task` event
//! ([`super::watcher::CLI_TASK_EVENT`]) and turns it into an ordinary turn:
//! it opens or continues a thread, pins the model, and sends the prompt
//! through the same path a typed message takes. These commands are the two
//! points where it has to tell Rust what it did.
//!
//! ## Why the window runs the task rather than the runtime
//!
//! The `TurnDriver` could run a dispatched task without any window. It would
//! also then be invisible: the transcript, the thread list, the tool cards and
//! the ability to steer or stop the turn all live in the Agent Window, and the
//! whole point of `aurora agent` is that you can *watch* the work. So the CLI
//! delivers an instruction and the window does what it always does with one.

use serde::{Deserialize, Serialize};

use super::bridge::{self, BridgeState, BRIDGE_FORMAT_VERSION};
use super::inbox::Inbox;
use super::mirror;

/// What the frontend reports when it starts a dispatched task.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CliTaskBinding {
    /// The task this turn belongs to.
    pub task_id: String,
    /// The turn about to run. Generated by the frontend, as every turn's is.
    pub turn_id: String,
    /// The thread it is running in — new or continued.
    pub thread_id: String,
    pub workspace_path: String,
    /// `providerId:modelKey`, when the dispatch named one.
    #[serde(default)]
    pub model: Option<String>,
    /// The caller's `--out` path, mirrored alongside the canonical transcript.
    #[serde(default)]
    pub out_path: Option<String>,
}

/// Attach a turn to a CLI task so its events reach the terminal.
///
/// Called by the Agent Window immediately before it starts the turn. From this
/// point until the turn ends, every event the runtime emits is also appended
/// to the task's transcript (see [`mirror`]).
///
/// Returns whether the binding was made. `false` means the turn was already
/// bound — a duplicate delivery of the same task — and the caller should not
/// start a second turn for it. That is the frontend's idempotency check, and
/// it matters because the watcher retries delivery while the window boots.
#[tauri::command]
pub async fn cli_task_bind(binding: CliTaskBinding) -> Result<bool, String> {
    Ok(mirror::bind(
        &binding.task_id,
        &binding.turn_id,
        &binding.thread_id,
        &binding.workspace_path,
        binding.model.as_deref(),
        binding.out_path.as_deref(),
    ))
}

/// Close a task's transcript without a turn having run.
///
/// For the cases where the window cannot start the work at all — no provider
/// configured, a workspace that has gone away, a model that no longer exists.
/// Without this the terminal would wait out its timeout on a file nothing was
/// ever going to write, and report "Aurora has not picked this task up" when
/// in truth Aurora picked it up and could not run it.
#[tauri::command]
pub async fn cli_task_fail(task_id: String, turn_id: String, error: String) -> Result<(), String> {
    // Bind first so there is a transcript to close. A task that failed before
    // it ever started has no turn, so nothing else will have bound it.
    mirror::bind(&task_id, &turn_id, "", "", None, None);
    mirror::finish(&turn_id, mirror::Outcome::Failed(&error));
    Ok(())
}

/// Every task waiting to be run, for a window that has just mounted.
///
/// The frontend calls this once on startup. It exists because Tauri events are
/// not buffered: a task claimed while the window was still booting was emitted
/// to nobody. The watcher retries, but a pull on mount closes the race
/// outright rather than relying on a retry landing in the right window.
#[tauri::command]
pub async fn cli_task_pending() -> Result<Vec<super::task::TaskRequest>, String> {
    Inbox::open().pending().map_err(|error| error.to_string())
}

/// Claim a pending task from the frontend.
///
/// The same rename-to-claim the watcher uses, exposed so a window that found a
/// task through [`cli_task_pending`] takes ownership the same way — one
/// claimer wins, and a second window cannot run the task twice.
#[tauri::command]
pub async fn cli_task_claim(task_id: String) -> Result<Option<super::task::TaskRequest>, String> {
    match Inbox::open().claim(&task_id) {
        Ok(request) => Ok(Some(request)),
        // Someone else got it. Not an error — it is the mechanism working.
        Err(super::inbox::InboxError::AlreadyClaimed(_)) => Ok(None),
        Err(super::inbox::InboxError::Io(error))
            if error.kind() == std::io::ErrorKind::NotFound =>
        {
            Ok(None)
        }
        Err(error) => Err(error.to_string()),
    }
}

// ── The bridge: what the Agent Window publishes about itself ────────────────

/// What the Agent Window reports about its own state.
///
/// Only the parts the window knows. Everything derivable here — the version,
/// this process's id, the timestamp, and the fact that a window is open at all
/// — is filled in by Rust, so the frontend cannot publish a state that says a
/// window is open while claiming to be some other process.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgePublish {
    /// The user's switch: may other agents send work to this Aurora.
    pub enabled: bool,
    /// The project the window is scoped to.
    #[serde(default)]
    pub workspace: Option<String>,
    /// The conversation on screen.
    #[serde(default)]
    pub thread_id: Option<String>,
    #[serde(default)]
    pub thread_title: Option<String>,
    /// `providerId:modelKey` that conversation runs on.
    #[serde(default)]
    pub model: Option<String>,
    /// Whether a turn is running.
    #[serde(default)]
    pub busy: bool,
}

/// Publish the Agent Window's state for other processes to read.
///
/// Called by the window on mount, whenever any published field changes, and on
/// teardown. Cheap enough to call freely: one small write-then-rename, and the
/// frontend only calls it when the snapshot actually differs.
#[tauri::command]
pub async fn aurora_bridge_publish(state: BridgePublish) -> Result<(), String> {
    bridge::publish(&BridgeState {
        version: BRIDGE_FORMAT_VERSION,
        enabled: state.enabled,
        // Asserted here rather than taken from the caller: this command can
        // only be invoked from a live webview, so a window demonstrably exists.
        window_open: true,
        pid: std::process::id(),
        workspace: state.workspace,
        thread_id: state.thread_id,
        thread_title: state.thread_title,
        model: state.model,
        busy: state.busy,
        updated_at: chrono::Utc::now().to_rfc3339(),
    })
    .map_err(|error| format!("could not publish the bridge state: {error}"))
}

/// Record that the Agent Window has gone.
///
/// The window calls this as it unloads. Rust also does it on window destroy,
/// because a webview that crashes never gets to run its own teardown — see the
/// `agent-window` handler in `lib.rs`.
#[tauri::command]
pub async fn aurora_bridge_clear() -> Result<(), String> {
    bridge::clear();
    Ok(())
}

/// What another agent needs in its config to reach this Aurora.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpClientConfig {
    /// The command another agent should run.
    pub command: String,
    /// Its arguments.
    pub args: Vec<String>,
    /// The whole thing as a block to paste into an MCP config file.
    pub snippet: String,
}

/// The config block for connecting another agent to this Aurora.
///
/// Built from this executable's own path rather than the bare name `aurora`.
/// The short name only works once the CLI has been put on PATH, and an agent
/// started by a launcher does not necessarily inherit the user's PATH anyway —
/// an absolute path works in every case, including several Aurora builds
/// installed side by side, where the bare name would reach whichever one won
/// the PATH race rather than the one the user is looking at.
#[tauri::command]
pub async fn aurora_mcp_client_config() -> Result<McpClientConfig, String> {
    let exe = std::env::current_exe()
        .map_err(|error| format!("could not find Aurora's own path: {error}"))?
        .to_string_lossy()
        .into_owned();

    let snippet = serde_json::to_string_pretty(&serde_json::json!({
        "mcpServers": {
            "aurora": { "command": exe, "args": ["mcp"] }
        }
    }))
    .map_err(|error| error.to_string())?;

    Ok(McpClientConfig {
        command: exe,
        args: vec!["mcp".to_string()],
        snippet,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_binding_deserialises_from_camel_case() {
        // The shape the frontend sends. A field renamed on one side and not
        // the other fails silently as a `None` model, so the wire form is
        // pinned here.
        let json = r#"{
            "taskId": "20260901T142233-7f3a91",
            "turnId": "01JQ8FTURN",
            "threadId": "01JQ8FTHREAD",
            "workspacePath": "E:\\project",
            "model": "fireworks:glm-5.2",
            "outPath": "run.jsonl"
        }"#;
        let binding: CliTaskBinding = serde_json::from_str(json).expect("parses");
        assert_eq!(binding.task_id, "20260901T142233-7f3a91");
        assert_eq!(binding.model.as_deref(), Some("fireworks:glm-5.2"));
        assert_eq!(binding.out_path.as_deref(), Some("run.jsonl"));
    }

    #[test]
    fn the_optional_fields_are_optional() {
        // A dispatch with no model named and no `--out` is the common case.
        let json = r#"{
            "taskId": "t",
            "turnId": "u",
            "threadId": "th",
            "workspacePath": "E:\\project"
        }"#;
        let binding: CliTaskBinding = serde_json::from_str(json).expect("parses");
        assert!(binding.model.is_none());
        assert!(binding.out_path.is_none());
    }
}
